### ISSUE TITLE
Sometimes more than three answers generated 

### ISSUE THREAD

**Issue by mkatenolan** [fac-17/tony-andy#15]
I can't tell you what triggered it but at some point while I was playing there was suddenly 4 answers instead of 3. 

![Screenshot 2019-09-27 at 10 40 13](https://user-images.githubusercontent.com/45820111/65759767-8d22b100-e113-11e9-9d2a-895c54ae4b61.png)

**Comment by georgiamshaw** [comment]
<img width="1440" alt="Screenshot 2019-09-27 at 10 43 14" src="https://user-images.githubusercontent.com/36238916/65760839-a4629e00-e115-11e9-8363-a9acb29fb92a.png">

we had a similar issue where the correct answer, when clicked, would add another correct answer to the page. slightly different problem I realise, but we solved it with Ollie's help by taking our array of buttons, creating a copy array, and then using that array. that way, we're not mutating our actual array, but a copy of it. something like that. here's a screenshot but if you want a better explanation, just ask.
<img width="1440" alt="Screenshot 2019-09-27 at 10 59 27" src="https://user-images.githubusercontent.com/36238916/65760975-e7bd0c80-e115-11e9-805f-423459680fb1.png">
